-- vim.keymap.set('n', '<Space>', '<NOP>')
vim.g.leader = ' '

-- lsp --
vim.keymap.set('n', '<leader>gd', vim.lsp.buf.definition)
vim.keymap.set('n', '<leader>gD', vim.lsp.buf.declaration)
vim.keymap.set('n', '<leader>gr', vim.lsp.buf.references)
vim.keymap.set('n', '<leader>gi', vim.lsp.buf.implementation)
vim.keymap.set('n', '<leader>rn', vim.lsp.buf.rename)
vim.keymap.set('n', '<leader>ca', vim.lsp.buf.code_action)
vim.keymap.set('n', '<leader>fc', vim.lsp.buf.format)
vim.keymap.set('n', '<leader>e', vim.diagnostic.open_float)
vim.keymap.set('n', 'K', vim.lsp.buf.hover)

vim.keymap.set('n', '<leader>gb', '<cmd>:GitBlameToggle')
vim.keymap.set('n', '<leader>ogb', '<cmd>:GitBlameOpenCommitURL')
vim.keymap.set('n', '<leader>ogb', '<cmd>:GitBlameOpenCommitURL')
vim.keymap.set('n', '<leader>ogl', require"gitlinker".get_buf_range_url("n", {action_callback = require"gitlinker.actions".open_in_browser}))
vim.keymap.set('v', '<leader>ogl', require"gitlinker".get_buf_range_url("v", {action_callback = require"gitlinker.actions".open_in_browser}))
vim.keymap.set('n', '<leader>sh', vim.lsp.buf.signature_help)
vim.keymap.set('n', '<C-p>', vim.diagnostic.goto_prev)
vim.keymap.set('n', '<C-n>', vim.diagnostic.goto_next)
vim.keymap.set('n', '<C-J>', '<cmd>:cnext')
vim.keymap.set('n', '<C-K>', '<cmd>:cprev')
-- vim.keymap.set('n', '<C-n>', ''<cmd>:NvimTreeToggle)'
vim.keymap.set('v', '<', '<gv')
vim.keymap.set('v', '>', '>gv')
vim.keymap.set('n', 'Y', 'y$')
-- vim.keymap.set('n', 'n', 'nzzzv')
-- vim.keymap.set('n', 'N', 'Nzzzv')
-- vim.keymap.set('n', 'J', 'mzJ`z')
local builtin = require('telescope.builtin')
vim.keymap.set('n', '<C-f>', builtin.find_files)
vim.keymap.set('n', '<C-g>', builtin.live_grep)
